openapi: 3.0.0
info:
  title: Spring PetClinic API
  description: API documentation for Spring PetClinic
  version: '1.0.0'
servers:
  - url: https://petclinic.example.com
paths:
  /owners/new:
    get:
      summary: Initiate creation of a new owner
      operationId: initCreationForm
      responses:
        '200':
          description: Owner creation form
    post:
      summary: Process creation of a new owner
      operationId: processCreationForm
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Owner'
      responses:
        '302':
          description: Redirect to the created owner's page
          headers:
            Location:
              schema:
                type: string
                format: uri
                example: '/owners/123'
components:
  schemas:
    Owner:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        address:
          type: string
        city:
          type: string
        telephone:
          type: string
      required:
        - firstName
        - lastName
        - address
        - city
        - telephone
