openapi: 3.0.0
info:
  title: Spring PetClinic API
  description: API documentation for Spring PetClinic
  version: '1.0.0'
servers:
  - url: https://petclinic.example.com
paths:
  /owners/{ownerId}/pets/new:
    get:
      summary: Initiate creation of a new pet
      operationId: initCreationForm
      parameters:
        - name: ownerId
          in: path
          required: true
          description: Unique identifier of the owner
          schema:
            type: integer
      responses:
        '200':
          description: Pet creation form
    post:
      summary: Process creation of a new pet
      operationId: processCreationForm
      parameters:
        - name: ownerId
          in: path
          required: true
          description: Unique identifier of the owner
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '302':
          description: Redirect to the owner's page
          headers:
            Location:
              schema:
                type: string
                format: uri
                example: '/owners/123'
components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        birthDate:
          type: string
          format: date
        type:
          $ref: '#/components/schemas/PetType'
      required:
        - name
        - birthDate
        - type
    PetType:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
        - name
