openapi: 3.0.0
info:
  title: Spring PetClinic API
  description: API documentation for Spring PetClinic
  version: '1.0.0'
servers:
  - url: https://petclinic.example.com
paths:
  /owners/{ownerId}/pets/{petId}/visits/new:
    get:
      summary: Initiate creation of a new visit
      operationId: initNewVisitForm
      parameters:
        - name: ownerId
          in: path
          required: true
          description: Unique identifier of the owner
          schema:
            type: integer
        - name: petId
          in: path
          required: true
          description: Unique identifier of the pet
          schema:
            type: integer
      responses:
        '200':
          description: Visit creation form
    post:
      summary: Process creation of a new visit
      operationId: processNewVisitForm
      parameters:
        - name: ownerId
          in: path
          required: true
          description: Unique identifier of the owner
          schema:
            type: integer
        - name: petId
          in: path
          required: true
          description: Unique identifier of the pet
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Visit'
      responses:
        '302':
          description: Redirect to the owner's page
          headers:
            Location:
              schema:
                type: string
                format: uri
                example: '/owners/{ownerId}'
components:
  schemas:
    Visit:
      type: object
      properties:
        id:
          type: integer
          format: int64
        date:
          type: string
          format: date
        description:
          type: string
      required:
        - date
        - description
